def chk(label, fn):
    try:
        r = fn()
        print("OK  ", label, "" if r is None else ("-> " + repr(r)))
    except Exception as e:
        print("FAIL", label, "->", type(e).__name__, e)

chk("import asyncio", lambda: __import__("asyncio"))
chk("import socket", lambda: __import__("socket"))
chk("import select", lambda: __import__("select"))
chk("select.poll", lambda: __import__("select").poll())
chk("import json", lambda: __import__("json"))
chk("import os", lambda: __import__("os"))
import os
chk("os.getpid", lambda: os.getpid())
chk("os.getppid", lambda: getattr(os,"getppid")())
chk("os.uname", lambda: os.uname())
chk("os.getcwd", lambda: os.getcwd())
chk("os.stat st_mtime", lambda: os.stat(".")[8])
chk("os.listdir", lambda: len(os.listdir(".")))
chk("os.getenv", lambda: os.getenv("HOME"))
chk("os.environ", lambda: getattr(os,"environ"))
chk("os.putenv", lambda: getattr(os,"putenv"))
chk("import time", lambda: __import__("time"))
chk("time.ticks_ms", lambda: __import__("time").ticks_ms())
chk("import _thread", lambda: __import__("_thread"))
chk("import ssl", lambda: __import__("ssl"))
chk("import tls", lambda: __import__("tls"))
chk("import hashlib", lambda: __import__("hashlib"))
chk("import binascii", lambda: __import__("binascii"))
chk("binascii.b2a_base64", lambda: __import__("binascii").b2a_base64(b"x"))
chk("import struct", lambda: __import__("struct"))
chk("struct.pack", lambda: __import__("struct").pack(">H", 1))
chk("import re", lambda: __import__("re"))
chk("import heapq", lambda: __import__("heapq"))
chk("compile()", lambda: compile("1+1","<s>","eval"))
chk("eval()", lambda: eval("1+1"))
chk("exec()", lambda: exec("x=5"))
